name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust as needed

      - name: Install Dependencies
        run: npm install

      # (Optional) Build the project if required
      - name: Build Project
        run: npm run build

      # Configure Git identity for the gh-pages deployment
      - name: Configure Git Identity
        run: |
          git config --global user.email "bharathmurthy1992@gmail.com"
          git config --global user.name "Kumar Murthy"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy